### ISSUE TITLE
crash: attempt to index field 'g' (a nil value)

### ISSUE THREAD

**Issue by mirsella** [anott03/nvim-lspinstall#6]
hello, thanks for the plugins. 
when i try to install any lsp with LspInstall it crash,  with every language I tried, with this error :
```
Error detected while processing function LspInstall:
line    3:
E5105: Error while calling lua chunk: ...vim/plugged/nvim-lspinstall/lua/nvim-lspinstall/init.lua:38: attempt to index field 'g' (a nil value)
```
nvim version : 
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

thanks, I'll be happy to provide any information I can and try anything

**Comment by anott03** [comment]
Hi,
I should have made this clear in the readme, but this extension is meant to be used with the built-in lsp that is currently only available in the nightly version of neovim. In addition to lsp, the nightly version has some additional lua compatibility that nvim 4 doesn't have, which is why you are getting that error. Unfortunately this means that if you want to use this plugin, you will need to upgrade to the latest nightly build.

**Comment by mirsella** [comment]
thanks for the quick answer, i `yay -S neovim-nightly-git` and it work :)
